language: node_js
node_js:
  - 'stable'
  - 'lts/*'
  - '12'
  - '10'
services:
  - redis-server
before_script:
  - npm run build
script:
  - npm run test
  - npm run coverage:failIfLow
after_success:
  - npm run coverage:coveralls
env:
  - NOHM_TEST_IOREDIS="false"
  - NOHM_TEST_IOREDIS="true"
branches:
  only: master
